config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ('/')
  root 'top#index'

	get 'shops', to: 'shop#index'
	get 'shops/:shop_id', to: 'shop#detail', as: 'shop_detail'
	get 'shops/:shop_id/videos', to: 'shop#videos', as: 'shop_videos'
  get 'shops/:shop_id/videos/:video_id', to: 'shop#video_detail', as: 'video_detail'

	get 'videos', to: 'video#index'

end

app/models/Shop.rb
class Shop < ApplicationRecord
	has_many :videos
end

app/models/Video.rb
class Video < ApplicationRecord
	belongs_to :shop
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/shop_controller.rb
class ShopController < ApplicationController

	def index

	end

	def detail
		@shop = Shop.find(params[:shop_id])
	end

	def videos
		@shop = Shop.find(params[:shop_id])
	end

	def video_detail
		@shop = Shop.find(params[:shop_id])
		@video = Video.find(params[:video_id])
		@other_videos = Video.where(shop_id: @shop.id)
	end
end

app/controllers/top_controller.rb
class TopController < ApplicationController

	def index

	end
end

app/controllers/video_controller.rb
class VideoController < ApplicationController

	def index
		@videos = Video.all
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
	<title>しずおか おまち留学</title>
	<meta name="viewport" content="width=device-width,initial-scale=1">
	<meta name="robots" content="noindex" />
	<%= csrf_meta_tags %>
	<%= csp_meta_tag %>

	<%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
	<script type="text/javascript" src="//code.jquery.com/jquery-1.11.0.min.js"></script>
	<script type="text/javascript" src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.min.css">
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.css">
	<script
		src="https://code.jquery.com/jquery-3.5.0.js"
		integrity="sha256-r/AaFHrszJtwpe+tHyNi/XCfMxYpbsRg2Uqn0x3s2zc="
		crossorigin="anonymous"></script>
	<%= yield(:add_css) %>
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.min.css">
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.css">
</head>

<body>
<div class="container">
	<%= yield %>
</div>

<a href="<%= videos_path %>">
	<img src="<%= asset_path('movie_cv.png') %>" alt="" class="movie_button">
</a>
<a href="<%= shops_path %>">
	<img src="<%= asset_path('shop_cv.png') %>" alt="" class="shop_button">
</a>

<script type="text/javascript" src="//code.jquery.com/jquery-1.11.0.min.js"></script>
<script type="text/javascript" src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
<%= yield(:add_js) %>
</body>
</html>

app/views/shop/detail.html.erb
<div class="shopDetail_head">
	<div class="shopDetail_head_shopImgContainer">
		<img src="<%= asset_path(@shop.image_path) %>" alt="店舗写真" class="el_shopImg">
	</div>
	<div class="shopDetail_head_catchcopyContainer">
		<p class="el_catchcopy"><%= @shop.catch %></p>
		<p class="el_name"><%= @shop.owner_name %></p>
	</div>
	<img src="<%= asset_path(@shop.owner_image_path) %>" alt="店主写真" class="shopDetail_head_shopkeeperImg">
</div>

<div class="shopDetail_profile">
	<div class="shopDetail_profile_inner">
		<p class="shopDetail_profile_title"><%= @shop.owner_name %>さんのプロフィール</p>
		<div class="shopDetail_profile_container">
			<%= @shop.owner_profile %>
		</div>
	</div>
</div>

<div class="shopDetail_desc">
	<p class="el_desc">
		<img src="<%= asset_path(@shop.description_image) %>" alt="店舗紹介写真" class="el_img">
		<%= @shop.description %></p>
</div>

<%- if @shop.videos.present? %>
	<div class="shopDetail_movie">
		<div class="shopDetail_movie_inner">
			<p class="shopDetail_movie_title"><%= @shop.owner_name %>さんのところに動画で短期留学！</p>
			<div class="shopDetail_movie_container">
				<%= render partial: 'video/video_list', locals: { videos: @shop.videos } %>
			</div>
			<%= link_to 'もっとみる', shop_videos_path(params[:shop_id]), class: 'moreBtn' %>
		</div>
	</div>
<%- end %>

<div class="shopDetail_studying">
	<p class="shopDetail_studying_title"><%= @shop.owner_name %>さんから直接学べる！お店留学！</p>
	<ul class="imageList">
		<li><img src="<%= asset_path('shops/milk/main.jpeg') %>" alt="" class="shopDetail_studying_img"></li>
		<li><img src="<%= asset_path('shops/cafe1.jpeg') %>" alt="" class="shopDetail_studying_img"></li>
		<li><img src="<%= asset_path('shops/cafe4.jpeg') %>" alt="" class="shopDetail_studying_img"></li>
	</ul>
	<div class="shopDetail_studying_points">
		<p class="">学べる3つのポイント</p>
		<ul class="">
			<li>◯<%= @shop.learn_point1 %></li>
			<li>◯<%= @shop.learn_point2 %></li>
			<li>◯<%= @shop.learn_point3 %></li>
		</ul>
	</div>
</div>

<div class="shopDetail_curriculum">
	<p class="shopDetail_curriculum_title">留学カリキュラム</p>
	<div class="shopDetail_curriculum_container">
		<div class="curriculum_parts">
			<p class="el_date">Day.1</p>
			<p class="el_desc"><%= @shop.learn_day1 %></p>
		</div>
		<%- if @shop.learn_day2.present? %>
			<div class="curriculum_parts">
				<p class="el_date">Day.2</p>
				<p class="el_desc"><%= @shop.learn_day2 %></p>
			</div>
		<%- end %>
		<%- if @shop.learn_day3.present? %>
			<div class="curriculum_parts">
				<p class="el_date">Day.3</p>
				<p class="el_desc"><%= @shop.learn_day3 %></p>
			</div>
		<%- end %>
	</div>

	<div class="shopDetail_curriculum_cta">
		<%= link_to 'お店に留学する', 'https://forms.gle/Xer4aaqC7ayVWeys7', class: 'cvBtn' %>
	</div>
</div>

<%- content_for :add_js do %>
	<script>
		$(function () {
			$('.imageList').slick();
		});
	</script>
<% end %>

app/views/shop/index.html.erb
<div class="shopIndex">
	<h2><img src="<%= asset_path('top/shop_search.png') %>" alt="お店でおまち留学"></h2>

	<ul>
		<%- Shop.all.each do |shop| %>
			<li>
				<a href="<%= shop_detail_path(shop.id) %>"><%= image_tag shop.image_path %></a>
				<h3><%= shop.name %></h3>
				<p class="address"><%= shop.address %></p>
				<p><%= truncate(shop.description, length: 50) %></p>
			</li>
		<%- end %>
	</ul>
</div>

app/views/shop/video_detail.html.erb
<div class="videoDetail">
	<div class="videoDetail_head">
		<p><%= @shop.name %> <%= @shop.owner_name %>さん</p>
		<h2><%= @video.name %></h2>
	</div>

	<div class="videoDetail_video">
		<iframe width="560" height="315" src="<%= @video.url %>" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
	</div>

	<section class="videoDetail_point">
		<h3 class="el_title">学べる3つのポイント</h3>
		<ul>
			<li><%= @video.point1 %></li>
			<li><%= @video.point2 %></li>
			<li><%= @video.point3 %></li>
		</ul>
	</section>

	<section class="videoDetail_cta">
		<a href="https://forms.gle/Xer4aaqC7ayVWeys7" class="cvBtn">動画を購入する ¥ 500- </a>
	</section>

	<%- if @other_videos.present? %>
		<section class="videoDetail_other">
			<h3><%= @shop.name %>の他の動画</h3>
			<%= render partial: 'video/video_list', locals: { videos: @other_videos } %>
		</section>
	<%- end %>

</div>

app/views/shop/videos.html.erb
<div class="videoIndex">
	<div class="videoIndex_head">
		<h2><%= @shop.name %>の動画一覧</h2>
	</div>

	<ul class="videoIndex_list">
		<%- @shop.videos.each do |video| %>
			<li>
				<a href="<%= video_detail_path(shop_id: video.shop_id, video_id: video.id) %>">
					<h3><%= video.name %></h3>
					<div class="videoIndex_list_thumb"><%= image_tag video.thumb_path %></div>
<!--					<div class="videoIndex_list_face"><%#= image_tag video.shop.owner_image_path %></div>-->
				</a>
				<p><%= video.description %></p>
			</li>
		<%- end %>
	</ul>
</div>

app/views/top/index.html.erb
<div class="header">
	<div class="header_inner">
		<img src="<%= asset_path('top/top_img.png') %>" alt="しずおか おまち留学" class="el_img">
	</div>
</div>

<div class="main">
	<div class="main_inner">

		<div class="part_desc">
			<img src="<%= asset_path('top/bg_bar.png') %>" alt="womoで「おまち留学」" class="el_img">
			<div class="part_desc_container">
				<p class="el_title">womoで「おまち留学」</p>
				<p class="el_text">
					「いつか、こういうカフェ<br>開いてみたいんだよね」<br>
					その言葉、womoで叶えませんか。<br>
					多くのお客様を迎える人気店や<br>
					人気教室を開かれる人のもとで<br>
					経営やブランディングのノウハウを学ぶ短期留学をWOMOがサポート。
				</p>
			</div>
			<img src="<%= asset_path('top/bg_bar.png') %>" alt="womoで「おまち留学」" class="el_img">
		</div>

		<div class="part_problem">
			<p class="el_title">こんなことでお悩みではありませんか？</p>
			<div class="part_problem_container">
				<img src="<%= asset_path('top/probrem1.png') %>" alt="しずおか おまち留学" class="el_img">
				<img src="<%= asset_path('top/probrem2.png') %>" alt="しずおか おまち留学" class="el_img">
				<img src="<%= asset_path('top/probrem1.png') %>" alt="しずおか おまち留学" class="el_img">
			</div>
			<p class="el_title">womoおまち留学がサポートします！</p>
		</div>

		<div class="part_options">
			<img src="<%= asset_path('top/search_title.png') %>" alt="留学先を探す" class="el_titleImg">
			<div class="part_options_container">
				<a href="<%= videos_path %>">
					<img src="<%= asset_path('top/movie_search.png') %>" alt="動画でおまち留学" class="el_img">
				</a>
				<a href="<%= shops_path %>">
					<img src="<%= asset_path('top/shop_search.png') %>" alt="お店でおまち留学" class="el_img">
				</a>
			</div>
		</div>

		<div class="part_success">
			<img src="<%= asset_path('top/success_patern.png') %>" alt="おまち留学のあと成功した人たち" class="el_titleImg">
			<div class="part_success_container">
				<div class="success_option">
					<div class="card csize tg1">
						<input id="tg01" style="display: none;" type="checkbox">
						<label id="omote" class="fuda cardSize" for="tg01"></label>
						<label id="ura" class="fuda cardSize" for="tg01"></label>
					</div>
					<p class="el_name">丸山いづみさん</p>
					<p class="el_desc">留学先：MILK</p>
				</div>
				<div class="success_option">
					<div class="card csize tg2">
						<input id="tg02" style="display: none;" type="checkbox">
						<label id="omote" class="fuda cardSize" for="tg02"></label>
						<label id="ura" class="fuda cardSize" for="tg02"></label>
					</div>
					<p class="el_name">山下彩友子さん</p>
					<p class="el_desc">留学先：CHAK</p>
				</div>
				<div class="success_option">
					<div class="card csize tg3">
						<input id="tg03" style="display: none;" type="checkbox">
						<label id="omote" class="fuda cardSize" for="tg03"></label>
						<label id="ura" class="fuda cardSize" for="tg03"></label>
					</div>
					<p class="el_name">沼上順香さん</p>
					<p class="el_desc">留学先：茶楽</p>
				</div>
			</div>
		</div>

		<div class="part_flow">
			<img src="<%= asset_path('top/flow.png') %>" alt="おまち留学後の流れ" class="el_img">
			<p class="el_text">ご希望の方は、WOMOスタッフがお答えします！</p>
			<a href="https://www.esz.co.jp/contact/" class="el_button">WOMOへ無料相談</a>
		</div>

		<div class="part_plan">
			<img src="<%= asset_path('top/plan.png') %>" alt="おまち留学後のプラン" class="el_img">
		</div>

		<div class="part_options">
			<img src="<%= asset_path('top/search_title.png') %>" alt="留学先を探す" class="el_titleImg">
			<div class="part_options_container">
				<a href="<%= videos_path %>">
					<img src="<%= asset_path('top/movie_search.png') %>" alt="動画でおまち留学" class="el_img">
				</a>
				<a href="<%= shops_path %>">
					<img src="<%= asset_path('top/shop_search.png') %>" alt="お店でおまち留学" class="el_img">
				</a>
			</div>
		</div>
	</div>
</div>
<div class="footer">
	<div class="footer_inner">
		<a href="<%= root_path %>">
			<img src="<%= asset_path('top/footer.png') %>" alt="お店でおまち留学" class="el_img">
		</a>
<!--		<div class="el_container">-->
<!--			<p>お問い合わせ</p>-->
<!--			<p>特定商取引法に基づく表記</p>-->
<!--			<p>運営会社</p>-->
<!--		</div>-->
<!--		<div class="el_container">-->
<!--			<p>利用規約/プライバシーポリシー</p>-->
<!--			<p>会員登録</p>-->
<!--			<p>©︎SHIZUOKA ONLINE</p>-->
<!--		</div>-->
	</div>
</div>

<%- content_for :add_js do %>
	<script>

	</script>
<%- end %>

app/views/video/_video_list.html.erb
<ul class="videoList">
	<%- videos.each do |video| %>
		<li>
			<a href="<%= video_detail_path(shop_id: video.shop_id, video_id: video.id) %>">
				<%= image_tag video.thumb_mini_path %>
				<p><%= truncate(video.description, length: 20) %></p>
			</a>
		</li>
	<%- end %>
</ul>

app/views/video/index.html.erb
<div class="videoIndex">
	<div class="videoIndex_head">
		<h2><img src="<%= asset_path('top/movie_search.png') %>" alt="動画でおまち留学"></h2>
	</div>

	<ul class="videoIndex_list">
		<%- @videos.each do |video| %>
			<li>
				<a href="<%= video_detail_path(shop_id: video.shop_id, video_id: video.id) %>">
					<h3><%= video.shop.name %> | <%= video.name %></h3>
					<div class="videoIndex_list_thumb"><%= image_tag video.thumb_path %></div>
<!--					<div class="videoIndex_list_face"><%#= image_tag video.shop.owner_image_path %></div>-->
				</a>
				<p><%= video.description %></p>
			</li>
		<%- end %>
	</ul>
</div>